### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by mars3142** [Trixt0r/spriter#12]
I'm using IntelliJ for my libGDX project and it would be nice to include this library via gradle build script. Can someone please upload it to a maven repository?

**Comment by jitpack-io** [comment]
Btw, you can already grab spriter as a Maven/Gradle dependency from: https://jitpack.io/#Trixt0r/spriter/662425e3b3

**Comment by mars3142** [comment]
@jitpack-io Nice, didn't know, that such a service is available.

**Comment by jitpack-io** [comment]
@mars3142 Yes, its a fairly new service

**Comment by denisk20** [comment]
Thanks for uploading the library to Maven. I was wondering if it's possible to also upload `LibGdxDrawer` and `LibGdxLoader` into Maven as separate library (which would depend on `com.github.trixt0r:Spriter:1.1`? Something like `com.github.trixt0r:Spriter-Libgdx:1.1`? It seems like the vast majority of people use this library with Libgdx, and it would be very convenient to not copy `LibGdxDrawer` and `LibGdxLoader` from Tests directory for every project.

**Comment by denisk20** [comment]
@Trixt0r what do you think about my last comment?

**Comment by Trixt0r** [comment]
The idea is nice. But I have not that much free time to do it.
I don't want to do any promises, but I'll try to upload it. If you have time, feel free to do it.

Maybe a seperate Spriter-LibGDX project on Github would be also a good idea, so we could focus on stuff like Scene2D, Box2D, GWT and stuff.

**Comment by denisk20** [comment]
@Trixt0r indeed separate Github project would be nice. I'll try to find time to extract the libgdx part. I just wish there were more hours in a day...

**Comment by Trixt0r** [comment]
For aynone who wants to use maven or gradle, use the "mvn" branch like this `https://raw.github.com/Trixt0r/spriter/mvn/`.
See `https://github.com/Trixt0r/spriter-examples` for an example with LibGDX.
This branch is now used to publish maven builds.
