### ISSUE TITLE
Use of Entity and Player class names

### ISSUE THREAD

**Issue by CupCoffee** [Trixt0r/spriter#16]
Hi,

I very often make use of the Entity/Player class while developing games. I don't really get why you would take up/use these for a "resource parser". Would it be an option to change this?

**Comment by Trixt0r** [comment]
Entity and Player are two different constructs. An entity holds the whole data parsed (animations, objects, files, etc.) from an SCML file. A player is used to process the data stored in an entity.

How would you change this?

**Comment by so3arbelnox** [comment]
I think (if I understand right) he is using his own class for Entity and Player and thinks it would be better to name these classes something else. Maybe SpriterEntity / SpriterPlayer? 

Its not a huge deal in my own project but I did have to rename some things in order to prevent having to type out the namespace each time.

**Comment by Trixt0r** [comment]
Well if naming is an issue, you could just put wrappers around them and name it whatever you want.
Since there are namespaces in Java, we don't have to prefix the class names.
I would not rename the classes only because of laziness.

**Comment by CupCoffee** [comment]
I get your point, but i posted it because the classnames didn't make very much sense to me. Especially since the names are used fairly often by game developers(like myself). Since game developers would be the primary "audience" for this library i could imagine why this would cause some frustrations. It is not about laziness but more about convenience of the developer.

If you are not going to consider this then this issue can be closed.
