### ISSUE TITLE
copyObjects 

### ISSUE THREAD

**Issue by wighawag** [Trixt0r/spriter#18]
another question:

what is the copyObjects for in Player ?

I see it defaults to true. what effect will it have if set to false?

**Comment by Trixt0r** [comment]
copyObjects is only meant to use if you plan to use multiple Player objects in different threads.
Internally this flag is used to do copies of rendering data, so Player objects with the same animation can be used independently in different threads.
If you are sure that every player object will be updated in the same thread you can set the flag to false. This should improve the performance a bit.
