### ISSUE TITLE
Hi, load error

### ISSUE THREAD

**Issue by tianqiujie** [Trixt0r/spriter#19]
SCMLReader reader = new SCMLReader(Gdx.files.internal("player/player.scml").read());
		LibGdxLoader loader = 	new LibGdxLoader(reader.getData());
		loader.load("player");

error:
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Could not find file handle player/p_torso_idle.png! Please check your paths.

the file is:
---player
   ---player.scml
   ---head
   ---feet
   ---torso
   ---arms
   ....

How to fix it? I am waitting for your reply. thank you

**Comment by Trixt0r** [comment]
p_torso.png is not listed in your folder.
