### ISSUE TITLE
Libgdx scene2d support

### ISSUE THREAD

**Issue by denisk20** [Trixt0r/spriter#22]
With `com.badlogic.gdx.scenes.scene2d.Actor#draw` method taking libgdx's `Batch` as a parameter and `com.brashmonkey.spriter.Drawer#draw` not doing so it makes it hard to use `Drawer` with `Actor`s. I understand that the intention was to keep `Drawer` interface generic (thus not relying on any libgdx classes) but it would be nice to be able to use it with scene2d. I have modified `Drawer`'s (and `LibGdxDrawer`'s) `draw()` methods locally to take `Batch` as a parameter which is obviously a hack.
Another solution would be to provide a setter in `LibGdxDrawer` to be able to set `batch` field before every `draw` call. That would keep generic `Drawer` intact, yet is still suboptimal since it would leave `LibGdxDrawer` "dirty" after each `draw()` call.
Are there any better solutions?

**Comment by Trixt0r** [comment]
Hmmm... tricky... I guess setting the batch before each draw call would be a okay-ish solution, but let me see what will come up to my mind.

I will try to look at to this and the other issues this weekend if possible.

Feel free to add more issues, if you find any.

**Comment by denisk20** [comment]
@Trixt0r Thanks! And thank you for providing us with the great tool.

**Comment by kalimaul** [comment]
I'm not sure if this is 100% related, but I'd like to note that I'm using this great tool with PlayN which also has a scene structure (although direct rendering is possible so I could integrate it fairly easily). It would be great if instead of direct rendering there was an option to translate spriter's scene structure and object transformations to each framework's own.

**Comment by Trixt0r** [comment]
Converting Spriters data structure to an arbitary scene structure is not the task of this project.

For LibGDX related stuff, use the gdx project https://github.com/Trixt0r/gdx-spriter
