### ISSUE TITLE
Pixel Art Drawing Mode

### ISSUE THREAD

**Issue by ghost** [Trixt0r/spriter#30]
I'm using the current version, and when I select pixel art mode, it doesn't draw as pixel art in libgdx.

**Comment by Trixt0r** [comment]
Whether an entity is rendered in pixel art mode or not is, as far as I know, not saved in the SCML/SCON file. This means the way the sprites are drawn in LibGDX (or any other library) is up to you. In LibGDX you can set the filter of the sprites with `sprite.getTexture().setFilter(Filter.Nearest, Filter.Nearest);` or something similar.

**Comment by Vandrake** [comment]
I tried opening the scml with notepad++ and it does say there pixel-art=1 I will try with the filter thing, maybe put it in there somehow. Thank you

**Comment by Trixt0r** [comment]
Use `Data.PixelMode` for accessing the drawing mode. The rest has to be done by your library of choice.
