### ISSUE TITLE
check if animation is finished

### ISSUE THREAD

**Issue by flagdizero** [Trixt0r/spriter#31]
Hi man! thank you very much for your work. I'm using it for my shooter platfor for android. I need to change the animation when one is finished.
For example transition between HITTEN and IDLE animations. I'dont find how to check this... Thank you sir!

**Comment by Trixt0r** [comment]
Use a PlayerListener

https://github.com/Trixt0r/spriter/blob/master/Spriter/src/com/brashmonkey/spriter/Player.java#L1027

**Comment by flagdizero** [comment]
thank you man! i will thank you in my game too
