### ISSUE TITLE
faulty animation

### ISSUE THREAD

**Issue by Yarima2** [Trixt0r/spriter#33]
I have no errors but the animation is drawn  in a strange way as seen in the two pictures at the bottom.
I changed nothing in the api and used your implementation for libGDX.
Here is the only souce code which is written by me:

```
package com.randomgamedevelopment.jarumi;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.g2d.Sprite;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.brashmonkey.spriter.Data;
import com.brashmonkey.spriter.Drawer;
import com.brashmonkey.spriter.Player;
import com.brashmonkey.spriter.SCMLReader;
import com.randomgamedevelopment.spriter.AnimationDrawer;
import com.randomgamedevelopment.spriter.AnimationLoader;


public class Jarumi extends ApplicationAdapter {



    Player player;
    ShapeRenderer renderer;
    SpriteBatch batch;
    Drawer<Sprite> drawer;
    AnimationLoader loader;
    OrthographicCamera cam;

    @Override
    public void create () {
        batch = new SpriteBatch();
        cam = new OrthographicCamera();
        cam.zoom = 1f;
        renderer = new ShapeRenderer();
        FileHandle handle = Gdx.files.absolute("D:\\workspace-neo\\Yarumi\\core\\assets\\data\\char18_014.scml");
        Data data = new SCMLReader(handle.read()).getData();

        loader = new AnimationLoader(data);
        loader.load(handle.file());

        drawer = new AnimationDrawer(loader, batch, renderer);

        player = new Player(data.getEntity(0));
        player.setAnimation(0);
        player.setPosition(300, 0);
    }

    @Override
    public void render () {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        player.update();
        drawer.draw(player);
        batch.end();
    }

    @Override
    public void dispose () {
        batch.dispose();
    }


}
```

![normal](https://cloud.githubusercontent.com/assets/20519159/17864249/8fad7834-689d-11e6-9b71-ec1a7900a3ee.png)
![problem](https://cloud.githubusercontent.com/assets/20519159/17864250/8fb0c3fe-689d-11e6-988f-5f9e03b1e497.png)

**Comment by Trixt0r** [comment]
I cannot reproduce it with the newest libGDX build.

**Comment by Yarima2** [comment]
OK - I'll do it set the project up , ensuring I use the latest build, and write if it worked

**Comment by Yarima2** [comment]
still the same problem:
here you can see the full project:
https://github.com/Yarima2/Jarumi

path to the animation is still absolute so you have to change it if you want to run it on your device

**Comment by Yarima2** [comment]
still the same problem:
here you can see the full project:
https://github.com/Yarima2/Jarumi

path to the animation is still absolute so you have to change it if you want to run it on your device

**Comment by Yarima2** [comment]
Thank you for your help.

I havestill the same problem but here is the new full projectfor you to get an overview:
https://github.com/Yarima2/Jarumi

**Comment by Trixt0r** [comment]
Is this problem actually happening in the tests, too?

**Comment by Yarima2** [comment]
Which tests are you talking about

**Comment by Trixt0r** [comment]
I mean the [SpriterTests folder](https://github.com/Trixt0r/spriter/tree/master/SpriterTests).

**Comment by Yarima2** [comment]
the LibGDX-Test runs flawless - i'll try to chane it bit for bit to my setup to see what the problemis

**Comment by Yarima2** [comment]
it seems like the scml-file is the problem because your LibGDX-Test running the sample animation I used has the same buggy result as in my project.

So here is the scml-file: https://dl.dropboxusercontent.com/u/5754740/Leaf%20Girl.zip 
It's a sample file which is made by the company that made spriter I think.

**Comment by Trixt0r** [comment]
I guess the problem is, that this animation was created with an older Spriter version at a time where the file format was not final.
However if I save the file with the newest Spriter version every animation plays fine.
