### ISSUE TITLE
Black blocks instead of images

### ISSUE THREAD

**Issue by flagdizero** [Trixt0r/spriter#35]
Hello man,
I use your library in my game, thanks a lot :+1: 
Some user tell me that sometimes the animations are composed by black blocks like in the photo...
I dont know when and why because in my phone never occur this error... Can you tell me something abotut that?

Thanks a lot man!

![photo93734874257665635](https://cloud.githubusercontent.com/assets/5861481/19089839/4564dc44-8a7c-11e6-868b-aef308ced776.jpg)

**Comment by Trixt0r** [comment]
Looks like the device can not load the sprites. This may be most likely a backend problem (LibGDX or whatever you are using) since the Spriter runtime does not affect rendering or loading resources at all.

Ask the users for the OS version, hardware specs, etc...

**Comment by Trixt0r** [comment]
So this seems to be a hardware or backend issue, therefore closing...
