### ISSUE TITLE
Improve the loading time

### ISSUE THREAD

**Issue by yuripourre** [Trixt0r/spriter#38]
I am using this library to load my characters dynamically during the game but it takes about 2 seconds to load (even if the character was loaded before). I am doing this in the main thread so the game hangs.

I know I could load the sprites in another thread but sounds like the loader needs some improvements.

I am planning to do this next month. Any considerations?

Thank you for this great library, btw. Saved me a lot of time.

**Comment by Trixt0r** [comment]
I think you won't get away with only one thread. Loading big image files, will take it's time, no matter how good you improve the SCML parser itself. I would recommend to delegate the loading on another thread, at least for images and sounds.

**Comment by yuripourre** [comment]
I am caching the images, I am having issues while parsing the file and loading the timeline.

I am planning to reuse those timelines to clone characters.

**Comment by yuripourre** [comment]
The class Player could have a method to create a new instance based on itself.

A [clone method](https://en.wikipedia.org/wiki/Clone_(Java_method)) will do the trick:

```
Player player2 = player1.clone()
```

**Comment by yuripourre** [comment]
I would be also useful to create that Street Fighter Alpha effect.

![Street Fighter Alpha Combo](http://vignette4.wikia.nocookie.net/streetfighter/images/4/48/Street_Fighter_Alpha_2_Gold.png/revision/latest?cb=20131212212819)

**Comment by yuripourre** [comment]
I solved this issue caching the Data also and then passing to the Loader, I think it is the safest way to load multiple sprites from the same source file.
