### ISSUE TITLE
setPosition with strange behavior

### ISSUE THREAD

**Issue by yuripourre** [Trixt0r/spriter#39]
After load a character, I call:
```
player.setPosition(x,y);
```

But the character is rendered at (0,0) and the position only changes after some draw calls (is possible to see the character then it is teleported to the right position).

Am I missing something?

P.S.: The position takes less than a second to update.

**Comment by Trixt0r** [comment]
Yout have to call setPosition before player.update

**Comment by yuripourre** [comment]
Thank you very much, it worked.
