### ISSUE TITLE
SpriterTest project link dead?

### ISSUE THREAD

**Issue by offcolor** [Trixt0r/spriter#40]
https://github.com/Trixt0r/spriter/tree/master/SpriterTests
This link is invalid. I want to see a demo for java2d I can't even find a tutorial for it :(

Where would I go to find a Java2D demo?

**Comment by Trixt0r** [comment]
Yes, I know, I need to re-link the projects.
The java2d implementation is [here](https://github.com/Trixt0r/java2d-spriter).
[All other examples are based on LibGDX.](https://github.com/Trixt0r/spriter-examples)
