### ISSUE TITLE
Only way to change size setScale()?

### ISSUE THREAD

**Issue by phunni** [Trixt0r/spriter#45]
Am I correct in thinking that the only way to change the size of the animation is to call setScale() on the Player? I'd hoped for a mechanism relative to world units rather than the size of the original images...

**Comment by Trixt0r** [comment]
Yes, that is the only way to change the size.

You could extend the base classes, to fit your needs. If you know the size of your animations, you could write your own method for setting the size by scaling the player instance.

I don't think that it is trivial to implement a generic solution for changing player size in non-relative values (if possible at all).
How would you handle all the different sizes of the animations?  You would end up scaling all animations which do not fit your set size anyways. This would result in really odd behavior.
